// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiblgqvxqgwiuuuxpdyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYmxncXZ4cWd3aXV1dXhwZHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDI3NDAsImV4cCI6MjA3MTAxODc0MH0.pbwAbanpMxyhtJSn8tCfR0HIFwZjpq--GyuOWdrirRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});